{% set data = load_setuptools()%}
package:
  name: hymo
  version: "0.1.6"

source:
  path: ../../

build:
  script: python -m pip install . --no-deps --ignore-installed -vv
  number: 1

requirements:
  build:
    - python >=3.11
    - pip
    - setuptools >=61
  host:
    - python >=3.11
    - pip
    - setuptools >=61
  run:
    - python >=3.11
    - pandas >=3.0.3

test:
  requires:
    - pytest
  imports:
    - hymo
  commands:
    - python -c "print('hello world')"
    - python -c "import sys, hymo; sys.exit(hymo.test())"

about:
  home: https://github.com/lucashtnguyen/hymo.git
  license:  BSD License
  summary: 'A Hydro Model reader '

